### ISSUE TITLE
Incompatibility with "Always Open In Container"? 

### ISSUE THREAD

**Issue by Q-Quan** [MoAllabbad/FF-Container-Default-Pages#1]
With this extension enabled, opening a URL which is set to open in container X by default will result in the new tab being redirected for the set home page of container X, instead of the URL. I would expect the set home page to only apply when opening the container in a new tab, and not override any specific URLs set to open in the container.

Firefox 95.0.2 on macOS 12.1.

**Comment by MoAllabbad** [comment]
This is a valid point! I haven't noticed this since I don't use the [MAC exstension](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) a lot. I have just started working on this and should push a fix soon. Thanks for reporting this conflict!

**Comment by Q-Quan** [comment]
@MoAllabbad No problem, thank you for the work on the extension!
