### ISSUE TITLE
Ability to add a home page for the default/blank container? 

### ISSUE THREAD

**Issue by pluralanomaly** [MoAllabbad/FF-Container-Default-Pages#3]
I've been using this extension and it has been fantastic so far, but the only issue I've had with it is I can't seem to find a way to customize the home page for when not using a container. Using extensions that would change the new tab/start page seems to override this extension. 

Is there a way to change the default home page that I may be missing? If not, if it's possible could I suggest adding this as a feature for this extension?

**Comment by MoAllabbad** [comment]
Hi there!

You're right. That's not something that this extension currently supports. But I think that it's a good addition. I will work on adding this feature soon. Thank you for the suggestion!

**Comment by MoAllabbad** [comment]
A new version incorporating the suggested feature is released on the Mozilla store. Please let me know if this is what you're looking for or if you had a different/better experience in mind. If not, I can close the issue. Thanks!
